#include "juego.h"
juego::juego(){
    mywindow.create(sf::VideoMode(900, 660, 32),"bomberman",sf::Style::Close);
    mywindow.setVerticalSyncEnabled(true);
}
void juego::run(){
    while (mywindow.isOpen())
	{
		sf::Event event;
		while (mywindow.pollEvent(event)){
			if (event.type == sf::Event::Closed)
				mywindow.close();
		}
		//mimapa.pintarmapa();
		myplayer.mover();
        mywindow.draw(mimapa);
        mywindow.draw(mimuro);
        mywindow.draw(mimuro1);
        mywindow.draw(mimuro2);
        mywindow.draw(mimuro3);
        mywindow.draw(mimuro4);
        mywindow.draw(mimuro5);
        mywindow.draw(mimuro6);
        mywindow.draw(mimuro7);
        mywindow.draw(mimuro8);
        mywindow.draw(mimuro9);
        mywindow.draw(mimuro10);
        mywindow.draw(mimuro11);
        mywindow.draw(mimuro12);
        mywindow.draw(mimuro13);
        mywindow.draw(mimuro14);
        mywindow.draw(mimuro15);
        mywindow.draw(mimuro16);
        mywindow.draw(mimuro17);
        mywindow.draw(mimuro18);
        mywindow.draw(mimuro19);
        mywindow.draw(mimuro20);
        mywindow.draw(mimuro21);
        mywindow.draw(mimuro22);
        mywindow.draw(mimuro23);
        mywindow.draw(mimuro24);
        mywindow.draw(mimuro25);
        mywindow.draw(mimuro26);
        mywindow.draw(mimuro27);
        mywindow.draw(mimuro28);
        mywindow.draw(mimuro29);
        mywindow.draw(mimuro30);
        mywindow.draw(mimuro31);
        mywindow.draw(mimuro32);
        mywindow.draw(mimuro33);
        mywindow.draw(mimuro34);
        mywindow.draw(mimuro35);
        mywindow.draw(mimuro36);
        mywindow.draw(mimuro37);
        mywindow.draw(mimuro38);
        mywindow.draw(mimuro39);
        mywindow.draw(mimuro40);
        mywindow.draw(mimuro41);
        mywindow.draw(mimuro42);
        mywindow.draw(mimuro43);
        mywindow.draw(mimuro44);
        mywindow.draw(mimuro45);
        mywindow.draw(mimuro46);
        mywindow.draw(mimuro47);
        mywindow.draw(mimuro48);
        mywindow.draw(mimuro49);
        mywindow.draw(mimuro50);
        mywindow.draw(mimuro51);
        mywindow.draw(mimuro52);
        mywindow.draw(mimuro53);
        mywindow.draw(mimuro54);
        mywindow.draw(mimuro55);
        mywindow.draw(mimuro56);
        mywindow.draw(mimuro57);
        mywindow.draw(mimuro58);
        mywindow.draw(mimuro59);
        mywindow.draw(mimuro60);
        mywindow.draw(mimuro61);
        mywindow.draw(mimuro62);
        mywindow.draw(mimuro63);
        mywindow.draw(mimuro64);
        mywindow.draw(mimuro65);
        mywindow.draw(mimuro66);
        mywindow.draw(mimuro67);
        mywindow.draw(mimuro68);
        mywindow.draw(mimuro69);
        mywindow.draw(mimuro70);
        mywindow.draw(mimuro71);
        mywindow.draw(myplayer);
		mywindow.display();
	}
}
